FastTradeWEB/Models/Statistics.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FastTradeBLL.DTO;
using System.ComponentModel.DataAnnotations;

namespace FastTradeWEB.Models
{
    public class Statistics
    {
        public int Number { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string MonthName { get; set; }
        public int Day { get; set; }
        public string DayOfWeek { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
        public int Sec { get; set; }
        public int Msec { get; set; }
        public int Count { get; set; }
        public DateTime DateForChart { get; set; }
        public DateTime DateFull { get; set; }
    }
}

FastTradeWEB/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using FastTradeBLL.Services;
using FastTradeBLL.Interfaces;
using FastTradeBLL.DTO;
using FastTradeWEB.Models;

namespace FastTradeWEB.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        ICategoryService categoryService;
        public NavController(ICategoryService serv)
        {
            categoryService = serv;
        }
        public PartialViewResult Menu(int? id)
        {
            ViewBag.SelectedCategory=id;
            Mapper.CreateMap<CategoryDTO, CategoryVM>();
            var categories = Mapper.Map<IEnumerable<CategoryDTO>, IEnumerable<CategoryVM>>(categoryService.GetCategories());
            return PartialView(categories);
        }
    }
}

FastTradeWEB/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using AutoMapper;
using FastTradeBLL.Services;
using FastTradeBLL.Interfaces;
using FastTradeBLL.DTO;
using FastTradeWEB.Models;
using FastTradeWEB.Service;


namespace FastTradeWEB.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        IAdService adService;
        IKindService kindService;
        ILocationService locationService;
        ITagService tagService;
        public UserController(IAdService servAd, IKindService servKind, ILocationService servLocation,ITagService servTag)
        {
            adService = servAd;
            kindService = servKind;
            locationService = servLocation;
            tagService = servTag;
        }
        public ActionResult Index()
        {
            string[] regions = locationService.GetRegionList("name");
            string[] ids = locationService.GetRegionList("id");
            ViewBag.Regions = regions;
            ViewBag.Ids = ids;

            var config = new MapperConfiguration(cfg => cfg.CreateMap<KindDTO, KindVM>());
            var mapper = config.CreateMapper();
            var kinds = mapper.Map<IEnumerable<KindDTO>, IEnumerable<KindVM>>(kindService.GetKinds());
            return View(kinds);
        }

        [HttpGet]
        public ActionResult GetAds(int? page, int categoryId=-1, int kindId=-1, int regionId=-1, int tagId=-1)
        {
            ViewBag.Category=categoryId;
            ViewBag.Kind = kindId;
            ViewBag.Region = regionId;
            ViewBag.Tag = tagId;
            int pageSize = 8;
            int pageNumber = (page ?? 1);

            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<AdDTO, AdVM>();
                cfg.CreateMap<KindDTO, KindVM>();
                cfg.CreateMap<CategoryDTO, CategoryVM>();
                cfg.CreateMap<LocationDTO, LocationVM>();
                cfg.CreateMap<UserDTO, UserVM>()
                    .ForMember("ConfirmPassword",opt=>opt.Ignore());
                cfg.CreateMap<TagDTO, TagVM>()
                    .ForMember(t=>t.InfoReviewTags,p=>p.Ignore());
                cfg.CreateMap<ImageDTO,ImageVM>();
            });
            //config.AssertConfigurationIsValid();
            var mapper = config.CreateMapper();
            var ads = mapper.Map<IEnumerable<AdDTO>, IEnumerable<AdVM>>(adService.GetAds((int)categoryId,(int)kindId,(int)regionId,(int)tagId));
            adService.Dispose();
            var adsSort = ads.OrderBy(a => a.DateAdd).Reverse();
            return PartialView(adsSort.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult GetAdbyAdId(int id)
        {
            int idUser = User.Identity.GetUserId<int>();
            string role = User.Identity.GetUserRole();
            ViewBag.UserId = idUser;
            ViewBag.Role = role;
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<AdDTO, AdVM>();
                cfg.CreateMap<KindDTO, KindVM>();
                cfg.CreateMap<CategoryDTO, CategoryVM>();
                cfg.CreateMap<LocationDTO, LocationVM>();
                cfg.CreateMap<UserDTO, UserVM>()
                    .ForMember("ConfirmPassword", opt => opt.Ignore());
                cfg.CreateMap<TagDTO, TagVM>()
                    .ForMember(t=>t.InfoReviewTags,p=>p.Ignore());
                cfg.CreateMap<ImageDTO, ImageVM>();
            });
            //config.AssertConfigurationIsValid();
            var mapper = config.CreateMapper();
            var ad = mapper.Map<AdDTO,AdVM>(adService.GetAdbyAdId(id));
            adService.Dispose();
            return View(ad);
        }

        public ActionResult GetTags()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<TagDTO, TagVM>()
                .ForMember(t=>t.Ads,p=>p.Ignore())
                .ForMember(t=>t.InfoReviewTags,p=>p.Ignore())
                );
            var mapper = config.CreateMapper();
            var tags = mapper.Map<IEnumerable<TagDTO>, IEnumerable<TagVM>>(tagService.GetTags());
            return PartialView(tags);
        }

        [HttpGet]
        public ActionResult RefreshTags()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<TagDTO, TagVM>()
                .ForMember(t => t.Ads, p => p.Ignore())
                .ForMember(t => t.InfoReviewTags, p => p.Ignore())
                );
            var mapper = config.CreateMapper();
            var tags = mapper.Map<IEnumerable<TagDTO>, IEnumerable<TagVM>>(tagService.GetTags());
            return PartialView(tags);
        }

        [HttpGet]
        public void IncrementCountReviewTag(int TagId)
        {
            tagService.Update(TagId);
        }

        [HttpGet]
        public ActionResult Statistics()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<TagDTO, TagVM>()
                           .ForMember(t => t.Ads, p => p.Ignore())
                           .ForMember(t => t.InfoReviewTags, p => p.Ignore())
                           );
            var mapper = config.CreateMapper();
            var tags = mapper.Map<IEnumerable<TagDTO>, IEnumerable<TagVM>>(tagService.GetTags());
            return View(tags);
        }

        [HttpGet]
        public ActionResult StatisticsForTag(int TagId)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<TagDTO, TagVM>()
                             .ForMember(t => t.Ads, p => p.Ignore());
                cfg.CreateMap<InfoReviewTagDTO,InfoReviewTagVM>();
            });
            var mapper = config.CreateMapper();
            var tag = mapper.Map<TagDTO,TagVM>(tagService.GetTag(TagId));
            return PartialView(tag);
        }

        public JsonResult GetReviewByTag(int TagId)
        {
            
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<TagDTO, TagVM>()
                             .ForMember(t => t.Ads, p => p.Ignore());
                cfg.CreateMap<InfoReviewTagDTO, InfoReviewTagVM>();
            });
            var mapper = config.CreateMapper();
            var tag = mapper.Map<TagDTO, TagVM>(tagService.GetTag(TagId));
            List<InfoReviewTagVM> ReviewTag = new List<InfoReviewTagVM>();
            ReviewTag = tag.InfoReviewTags.ToList();

            GetStatistics stat = new GetStatistics(ReviewTag);
            List<Statistics> statList = stat.ListStat();

            return Json(statList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetStatByChartAjax(int TagId)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<TagDTO, TagVM>()
                             .ForMember(t => t.Ads, p => p.Ignore());
                cfg.CreateMap<InfoReviewTagDTO, InfoReviewTagVM>();
            });
            var mapper = config.CreateMapper();
            var tag = mapper.Map<TagDTO, TagVM>(tagService.GetTag(TagId));
            List<InfoReviewTagVM> ReviewTag = new List<InfoReviewTagVM>();
            ReviewTag = tag.InfoReviewTags.ToList();

            GetStatistics stat = new GetStatistics(ReviewTag);
            stat.ListStat();
            List<StatisticsForChart> statForChart = stat.ListStatForChart();
            return Json(statForChart, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetStatByChart(int TagId)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<TagDTO, TagVM>()
                             .ForMember(t => t.Ads, p => p.Ignore());
                cfg.CreateMap<InfoReviewTagDTO, InfoReviewTagVM>();
            });
            var mapper = config.CreateMapper();
            var tag = mapper.Map<TagDTO, TagVM>(tagService.GetTag(TagId));
            List<InfoReviewTagVM> ReviewTag = new List<InfoReviewTagVM>();
            ReviewTag = tag.InfoReviewTags.ToList();

            GetStatistics stat = new GetStatistics(ReviewTag);
            stat.ListStat();
            List<StatisticsForChart> statForChart = stat.ListStatForChart();
            if (statForChart != null)
            {
                return PartialView(statForChart);
            }
            else
            {
                return new EmptyResult();
            }
        }
            
    }
}

FastTradeWEB/Views/User/GetAdbyAdId.cshtml
@using Microsoft.Owin.Security;
@using System.Security.Claims;
@using System.Security.Principal;

@model FastTradeWEB.Models.AdVM

@{
    ViewBag.Title = "FastTrade.com";
    Layout = "~/Views/Shared/_MainView.cshtml";
    
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "allContent",
        OnBegin = "startLoadingAnimation()",
        OnComplete = "stopLoadingAnimation()",
        Confirm="Вы действительно хотите удалить данное объявление?"
    };
}

<br />
<br />
<div class="row">
    <div class="col-xs-12">
        
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Общая информация</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Kind.Name):
                        <div>
                            @Html.DisplayFor(model => model.Kind.Name)
                        </div>
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Category.Name):
                        <div>
                            @Html.DisplayFor(model => model.Category.Name)
                        </div>
                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.LocationNew.LocationName):
                        <div>
                            @Html.DisplayFor(model => model.LocationNew.LocationName)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <p>
                            <div>
                                @Html.LabelFor(model => model.Header, new { })
                                <div>
                                    @Html.DisplayFor(model => model.Header)
                                </div>
                            </div>
                        </p>
                        <p>
                            <div>
                                @Html.LabelFor(model => model.Description, new { })
                                <div>
                                    @Html.DisplayFor(model => model.Description)
                                </div>
                            </div>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.User.FirstName)
                                <div>
                                    @Html.DisplayFor(model => model.User.FirstName)
                                </div>
                            </div>
                        </div>
                    </p>
                </div>

                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.User.Phone)
                                <div>
                                    @Html.DisplayFor(model => model.User.Phone)  <br />
                                </div>
                            </div>
                        </div>
                    </p>
                </div>
                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.Address)
                                <div>
                                    @Html.DisplayFor(model => model.Address)
                                </div>
                            </div>
                        </div>
                    </p>
                </div>
                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.Price)
                                <div>
                                    @Html.DisplayFor(model => model.Price, new { }) BYR <br />
                                </div>
                            </div>
                        </div>
                    </p>
                </div>
                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.Images)
                                <div>
                                    @if(Model.Images.Count>0)
                                    { 
                                        foreach (var image in Model.Images)
                                        {
                                            <div class=" thumbnail col-xs-2">
                                                <img class="clickImage img-responsive" src=@image.PathToOriginal alt="" />
                                            </div>
                                        }
                                    }
                                    else
                                    {
                                         <span>
                                             Изображения отсутствуют.
                                         </span> 
                                    } 
                                </div>
                            </div>
                        </div>
                    </p>
                </div>
                <div class="row">
                    <p>
                        <div class="col-xs-12">
                            <div>
                                @Html.LabelFor(model => model.Tags)
                                <div>
                                    @if (Model.Tags.Count > 0)
                                    {
                                        foreach (var tag in Model.Tags)
                                        {
                                            <button id="tagOnlyRead" class="btn btn-default">@tag.TagName</button>
                                        }
                                    }
                                    else
                                    {
                                        <span>
                                            Теги отсутствуют.
                                        </span>
                                    }
                                    
                                </div>
                            </div>
                        </div>
                    </p>
                </div>
                <br />
                <br />
                @if (ViewBag.UserId == Model.User.UserId || ViewBag.Role=="Admin")
                {
                    <div class="text-right">
                        @Ajax.ActionLink("Удалить", "PersonalAdsDelete", "Manage", new { AdId = Model.AdId }, ajaxOpts, new {@class = "btn btn-danger" })
                        @Html.ActionLink("Редактировать", "PersonalAdsEdit", "Manage", new { id = Model.AdId }, new { target = "_blank", @class = "btn btn-success" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<br />
<br />
<br />
<br />

FastTradeWEB/Views/User/GetAds.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FastTradeWEB.Models.AdVM>


<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "FastTrade.com";
}

    <div id="content">
        @if (Model.Count > 0)
        {
            <div class="row masonry" data-columns>
                @foreach (var ad in Model)
                {
                    <div class="salvatore" id="item">
                        <div class="thumbnail">
                            
                            @if (ad.Images.Count > 0)
                            {
                                foreach (var image in ad.Images)
                                {
                                    <div id="imageBox">
                                        <img class="clickImage" src=@image.PathToOriginal alt=""/>
                                    </div>
                                    break;
                                }
                            }
                            @if (ad.Images.Count == 0)
                            {
                                <img src="http://placehold.it/300x240" alt="" />
                            }
                            <div class="caption">
                                <div id="header">
                                    <div>
                                        <p class="text-primary">@ad.Header</p>
                                    </div>
                                </div>
                                <div id="category_and_kind">
                                    <p id="kindAd" class="text-muted text-left">@ad.KindName/@ad.CategoryName</p>
                                </div>
                                <div id="dateAdAdd">
                                    <p id="dateAd" class="text-muted">@ad.DateAdd</p>
                                </div>
                                <div id="price">
                                    <p id="priceAd">@ad.Price.ToString("c")</p>
                                </div>
                                @Html.ActionLink("Подробнее", "GetAdbyAdId", "User", new { id = ad.AdId }, new { target = "_blank", @class = "btn btn-block btn-info btn-sm" })
                            </div>
                        </div>
                    </div>
                }
            </div>
            <p>
                Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
            </p>


            @Html.PagedListPager(Model, page => Url.Action("GetAds", "User", new { page, categoryId = ViewBag.Category, kindID = ViewBag.Kind, regionId = ViewBag.Region, tagId = ViewBag.Tag }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
            {
                HttpMethod = "GET",
                UpdateTargetId = "content",
                OnBegin = "startLoadingAnimation()",
                OnComplete = "stopLoadingAnimation()"
            }))
        }
        else
        {
            <h4 class="text-center">
                По данному фильтру объявлений не найдено.
            </h4> 
        }
    </div>

    <script src="~/Scripts/salvattore.min.js"></script>
<script type="text/javascript" ax:repeat="0" src="~/Scripts/popup_img.js"></script>

FastTradeWEB/Views/User/GetStatByChart.cshtml
@model List<FastTradeWEB.Models.StatisticsForChart>
@using FastTradeWEB.Models

<script type="text/javascript">
    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(drawBasic);

    function drawBasic() {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Дата');
        data.addColumn('number', 'Запросы');

        var count=@Model.Count;
        var k=0;
        var months = new Array(count);
        var numbers= new Array(count);
        var years=new Array(count);
        @{

            StatisticsForChart[] statArray = new StatisticsForChart[Model.Count];
            statArray = Model.ToArray();
        }

        @foreach(var stat in Model)
        {
            <text>
        months[k]='@stat.MonthName';
            numbers[k]=@stat.Count;
            years[k]=@stat.Year;
            k++;
            </text>
        }

        for(var i=0;i<count;i++)
        {
            //var date=months[i].concat(years[i].toString());
            data.addRow(
            [months[i], numbers[i]]);
        }

        var options = {
            title: 'Количество запросов за месяц',
            hAxis: {
                title: 'Месяц года',
            },
            vAxis: {
                title: 'Количество запросов'
            }
        };

        var chart = new google.visualization.ColumnChart(
          document.getElementById('chart_div'));

        chart.draw(data, options);
    }
</script>
<div id="chart_div"></div>

FastTradeWEB/Views/User/GetTags.cshtml
@model IEnumerable<FastTradeWEB.Models.TagVM>

@{
    Layout = null;
    //ViewBag.Title = "Персональные данные";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "basicAdInformation",
        OnBegin = "startLoadingAnimation()",
        OnComplete = "stopLoadingAnimation()"
    };
}
<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <a href="#spoilerTags" data-toggle="collapse" class="btn btn-block btn-info btn-sm spoiler collapsed">
                    <span>Поиск по тегам <span id="searchByTag">(Все тэги)</span></span> <span class="caret"></span>
                </a>
            </div>
            @*<div class="col-xs-1">
                @Ajax.ActionLink("Обновить", "", new { }, ajaxOpts, new { @class = "btn btn-sm btn-block btn-default" })
            </div>*@
        </div>
        <div class="collapse" id="spoilerTags">
            <div class="well pre-scrollable text-center" id="boxTags">
                <a id="refreshTags" @*type="button"*@ class="btn btn-sm btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                </a>
                <button class="btn btn-info btn-sm active" id="filter_tag" data-tag-id="-1" data-tag-name="(Все тэги)">
                    Все тэги
                </button>
                @foreach (var tag in Model)
                {
                    <button class="btn btn-info btn-sm" id="@tag.TagName" data-tag-id="@tag.TagId" data-tag-name="(@tag.TagName)">
                        <span class="badge badge-default">@tag.CountAd</span> @tag.TagName <span class="badge badge-error">@tag.CountReq</span>
                    </button>
                }
            </div>
        </div>
    </div>
</div>

FastTradeWEB/Views/User/Index.cshtml
@model IEnumerable<FastTradeWEB.Models.KindVM>

@{
    ViewBag.Title = "FastTrade.com";
    Layout = "~/Views/Shared/_MainView.cshtml";
}

@Html.Action("GetTags", "User")
<br />
<div class="row">
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-4">
        @Html.Action("Menu", "Nav")
    </div>

    <div class=" col-lg-10 col-md-9 col-sm-8 col-xs-8">
        <div>
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                    <div class="btn-group" id="nav_kind" data-toggle="buttons">
                        <label class="btn btn-info active" id="filter_kind" data-kind-id="-1">
                            <input type="radio" name="options" autocomplete="off" checked> Все типы
                        </label>
                        @foreach (var kind in Model)
                        {
                            <label class="btn btn-info" id="@kind.Name" data-kind-id="@kind.KindId">
                                <input type="radio" name="options" autocomplete="off"> @kind.Name
                            </label>
                        }
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3" id="mySelect">
                    <select class="selectpicker" data-style="btn-info" id="filter_region">
                        <option data-id-region="-1">Вся Беларусь</option>
                        @for (int i = 0; i < ViewBag.Regions.Length; i++)
                        {
                            <option data-id-region="@ViewBag.Ids[i]">@ViewBag.Regions[i]</option>
                        }
                    </select>
                </div>
            </div>
            <div>
                <br />
                @Html.Action("GetAds")
            </div>
        </div>
    </div>
</div>

FastTradeWEB/Views/User/RefreshTags.cshtml
@model IEnumerable<FastTradeWEB.Models.TagVM>

<div class="well pre-scrollable text-center" id="boxTags">
    <button id="refreshTags" type="button" class="btn btn-sm btn-default" aria-label="Left Align">
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
    </button>
    <button class="btn btn-info btn-sm active" id="filter_tag" data-tag-id="-1" data-tag-name="(Все тэги)">
        Все тэги
    </button>
    @foreach (var tag in Model)
    {
        <button class="btn btn-info btn-sm" id="@tag.TagName" data-tag-id="@tag.TagId" data-tag-name="(@tag.TagName)">
            <span class="badge badge-default">@tag.CountAd</span> @tag.TagName <span class="badge badge-error">@tag.CountReq</span>
        </button>
    }
</div>
<script src="~/Scripts/myScript.js"></script>

FastTradeWEB/Views/User/Statistics.cshtml
@model IEnumerable<FastTradeWEB.Models.TagVM>

@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/_MainView.cshtml";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "basicAdInformation",
        OnBegin = "startLoadingAnimation()",
        OnComplete = "stopLoadingAnimation()"
    };
}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="~/Scripts/JqGrid_Chart.js"></script>
<h3 class="text-center">Статистика</h3>
<div class="row">
    <div class="col-xs-12">
        <div>
            <div class="well pre-scrollable text-center" id="tagForStatistics">
                @foreach (var tag in Model)
                {
                    <button class="btn btn-info btn-sm" id="@tag.TagName" data-tag-id="@tag.TagId" data-tag-name="(@tag.TagName)">
                        <span class="badge badge-default">@tag.CountAd</span> @tag.TagName <span class="badge badge-error">@tag.CountReq</span>
                    </button>
                }
            </div>
        </div>
    </div>
</div>
<div id="statisticsForTag">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</div>

FastTradeWEB/Views/User/StatisticsForTag.cshtml
@model FastTradeWEB.Models.TagVM

@{
    Layout = null;
}
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Активность тэга @Model.TagName</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12">
                <h4>
                    Количество объявлений: @Model.CountAd
                </h4>
                <h4>
                    Количество запросов: @Model.CountReq
                </h4>
                <label id="tagId" data-tagid="@Model.TagId"></label>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                @Html.Action("GetStatByChart", "User", new { TagId = Model.TagId })
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                @if (Model.CountReq != 0)
                {
                    <table id="jqg"></table>
                }
            </div>
        </div> 
    </div>
</div>
   
    

<script type="text/javascript">
</script> 
<script src="~/Scripts/jqGrid/i18n/grid.locale-ru.js"></script>
<script src="~/Scripts/jqGrid/jquery.jqGrid.min.js"></script>
<script src="~/Scripts/JqGrid_Chart.js"></script>